name: whiskers

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@v1
    with:
      args: |
        templates/fcitx5.tera
        templates/highlight-svg.tera
        templates/panel-svg.tera
    secrets: inherit
